-- ==============================================================================
-- Migration: Portfolio Settings & Storage Policies for Persistent Profile Photo & Full Site Data
-- Table: portfolio_settings
-- Bucket: portfolio-images (Public)
-- ==============================================================================

-- 1. Create portfolio_settings table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.portfolio_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  profile_photo_url TEXT,
  site_data JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Add site_data column if table already exists
ALTER TABLE public.portfolio_settings ADD COLUMN IF NOT EXISTS site_data JSONB;

-- 3. Insert initial row with id=1
INSERT INTO public.portfolio_settings (id, profile_photo_url, updated_at)
VALUES (1, NULL, now())
ON CONFLICT (id) DO NOTHING;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.portfolio_settings ENABLE ROW LEVEL SECURITY;

-- 5. Drop old policies if they exist to avoid conflict
DROP POLICY IF EXISTS "Allow public read access on portfolio_settings" ON public.portfolio_settings;
DROP POLICY IF EXISTS "Allow insert or update on portfolio_settings" ON public.portfolio_settings;

-- 6. Create RLS Policies for portfolio_settings
CREATE POLICY "Allow public read access on portfolio_settings"
ON public.portfolio_settings
FOR SELECT
TO anon, authenticated, public
USING (true);

CREATE POLICY "Allow insert or update on portfolio_settings"
ON public.portfolio_settings
FOR ALL
TO anon, authenticated, public
USING (true)
WITH CHECK (true);

-- ==============================================================================
-- 7. Storage Bucket Policies for 'portfolio-images'
-- ==============================================================================

-- Ensure bucket exists and is public
INSERT INTO storage.buckets (id, name, public)
VALUES ('portfolio-images', 'portfolio-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Access for portfolio-images" ON storage.objects;
CREATE POLICY "Public Access for portfolio-images"
ON storage.objects
FOR SELECT
TO anon, authenticated, public
USING (bucket_id = 'portfolio-images');

DROP POLICY IF EXISTS "Allow upload to portfolio-images" ON storage.objects;
CREATE POLICY "Allow upload to portfolio-images"
ON storage.objects
FOR INSERT
TO anon, authenticated, public
WITH CHECK (bucket_id = 'portfolio-images');

DROP POLICY IF EXISTS "Allow update to portfolio-images" ON storage.objects;
CREATE POLICY "Allow update to portfolio-images"
ON storage.objects
FOR UPDATE
TO anon, authenticated, public
USING (bucket_id = 'portfolio-images');
